source/blog/urls.py
from django.urls import path
from .views import all_blog, detail

app_name = "blog"
urlpatterns = [
    path("", all_blog, name="all_blog"),
    path("<int:id>/", detail, name="detail"),
]

source/myportfolio/urls.py
from django.urls import path
from .views import home

app_name = "port"
urlpatterns = [
    path('', home, name="home-view"),
]

source/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myportfolio.urls')),
    path('blog/', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=256)
    date = models.DateField()

    def __str__(self):
        return self.title

source/myportfolio/models.py
from django.db import models


class project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=256)
    image = models.ImageField(upload_to='myportfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

source/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blog(request):
    pro = Blog.objects.order_by('-date')
    context = {
        "projects": pro
    }
    return render(request, "blog_hello.html", context)


def detail(request, id):
    obj = get_object_or_404(Blog, pk=id)
    context = {
        "blog": obj
    }
    return render(request, 'blog_detail.html', context)

source/myportfolio/views.py
from django.shortcuts import render
from .models import project


def home(request):
    proj = project.objects.all()
    context = {
        "projects": proj
    }
    return render(request, "home.html", context)

source/blog/templates/blog_detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ blog.title }}</h1>
    <h2>--{{ blog.date|date:"F jS Y" }}--</h2>
    <p>
        {{ blog.description|safe }}
    </p>
{% endblock %}

source/blog/templates/blog_hello.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
         <h2>Catt has written {{ projects.count }} blog{{ projects.count|pluralize }}</h2>
        {% for i in projects %}
            <a href="{% url 'blog:detail' i.id %}"><h2>{{ i.title }}</h2></a>
            <p>{{ i.description|striptags|truncatechars:100 }}</p>
            <h3>{{ i.date|date:"M d Y"|upper }}</h3>
        {% endfor %}
    </div>
{% endblock %}

source/myportfolio/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static 'portfolio/Logo.png' %}">

  <title>Sat Paing</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'port:home-view' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <span>Sat Paing</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/english.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/nick-walter/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/ZappyCode" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blog' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

source/myportfolio/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/satpaing.jpg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Catt is Commander-in-Chief at The Miracel and lives in Downtown Yangon 😊</h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}